
print("")
print("██████╗  ██████╗ ██████╗ ████████╗ █████╗ ██╗     ")
print("██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██║     ")
print("██████╔╝██║   ██║██████╔╝   ██║   ███████║██║     ")
print("██╔═══╝ ██║   ██║██╔══██╗   ██║   ██╔══██║██║     ")
print("██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║███████╗")
print("╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝")
print("				         ██╗██╗   ██╗███╗   ███╗██████╗ ")
print("				         ██║██║   ██║████╗ ████║██╔══██╗")
print("				         ██║██║   ██║██╔████╔██║██████╔╝")
print("				    ██   ██║██║   ██║██║╚██╔╝██║██╔═══╝ ")
print("				    ╚█████╔╝╚██████╔╝██║ ╚═╝ ██║██║     ")
print("				     ╚════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝   ")

print()
print("                    oooooOOOOOOOOOOOOOOOOooooo ")
print("                  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ")
print("                 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII ")
print("                HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH ")
print("               zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz ")
print("    .<><><><><><><><><><><><><><><><><><><><><><><><><><><><>. ")
print("  /XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\ ")
print("/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\ ")
print("\XXX[  ]XXX[  ]XXXX[  ]XXXX[  ]XXXX[  ]XXXX[  ]XXXX[  ]XXX[  ]XXX/ ")
print("  \XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ ")
print("      ~~~~\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/~~~~ ")
print("               /   ~~~<><><><><><><><><><>~~~   \ ")
print("              /      /       |   |        \      \ ")
print("             /     /               |        \     \ ")
print("            /    /           |                \    \ ")
print("           /   /               |   |            \   \ ")
print("          /  /               |                    \  \ ")
print("        _/_/                     | |                \_\_ ")
